name: Automated release

on: [push]

jobs:
  build:
     runs-on: ubuntu-latest
     
     strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

     steps:
       - uses: actions/checkout@v1
       - name: Use Node.js ${{ matrix.node-version }}
         uses: actions/setup-node@v1
         with:
            node-version: ${{ matrix.node-version }}
       - name: npm install and test
         run: |
            npm ci
            npm test
         env:
            CI: true
  publish:

    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - name: Automated release
      uses: mikeal/merge-release@2.2.6
      env:
        CI: true
