name: Automated release

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
        name: Checkout code
      - uses: borales/actions-yarn@v2.0.0
        name: install deps
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.0.0
        name: run tests
        with:
          cmd: test
        env:
          CI: true
  publish:
    runs-on: ubuntu-latest
    needs: [ci]

    steps:
      - uses: actions/checkout@v1
        name: Checkout code
      - uses: borales/actions-yarn@v2.0.0
        name: publish
        with:
          cmd: publish
        env:
          CI: true
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
